[package]
name = "vole"
version = "0.1.0"
edition = "2024"

[dependencies]
schmivitz = { git = "https://github.com/GaloisInc/swanky"}
folding-schemes = { git = "https://github.com/privacy-scaling-explorations/sonobe", package = "folding-schemes"}
wasmer = { version = "2.3.0", features = ["js"] }

# Arkworks family
ark-bn254 = { version = "^0.5.0", default-features = false }
ark-circom = { git = "https://github.com/winderica/circom-compat", branch = "arkworks-next", default-features = false }
ark-crypto-primitives = { version = "^0.5.0", default-features = false }
ark-ec = { version = "^0.5.0", default-features = false }
ark-ff = { version = "^0.5.0", default-features = false }
ark-groth16 = { version = "^0.5.0" }
ark-grumpkin = { version = "^0.5.0", default-features = false }
ark-mnt4-298 = { version = "^0.5.0" }
ark-mnt6-298 = { version = "^0.5.0" }
ark-pallas = { version = "^0.5.0" }
ark-poly = { version = "^0.5.0", default-features = false }
ark-poly-commit = { version = "^0.5.0" }
ark-r1cs-std = { version = "^0.5.0", default-features = false }
ark-relations = { version = "^0.5.0", default-features = false }
ark-serialize = { version = "^0.5.0" }
ark-snark = { version = "^0.5.0", default-features = false }
ark-std = { version = "^0.5.0", default-features = false }
ark-vesta = { version = "^0.5.0" }

# This allows the crate to be built when targeting WASM.
# See more at: https://docs.rs/getrandom/#webassembly-support 
# [target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
# getrandom = { workspace = true, features = ["js"] }

[[example]]
name = "sha256"
path = "../examples/sha256.rs"
